### PR TITLE
[FEATURE] Global palm

### PR DESCRIPTION
**Pull request by jakeberesford-palmetto**
## Pull request checklist

Before submitting your PR, please review the following checklist:

- [x] Consider adding a unit test if your PR resolves an issue.
- [x] All new and existing tests pass locally (`palm test`)
- [x] Lint (`palm lint`) has passed locally and any fixes were made for failures
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Breaking changes

- [ ] Check if this pull request introduces a breaking change

## What does this implement/fix? Explain your changes.

Being able to run palm outside of existing git projects unlocks a ton of new possibilities for palm.
* Use discover_repository to allow us to raise and handle a custom exception in the case we are outside of a git repo
* Change the implementation of branch detection so that we have proper control over when that check is executed
* Update the implementation of palm_config.plugins to be a list with setters
* Implement a global 'setup' plugin for OOTB global functionality, like new project scaffolding.

## Does this close any currently open issues?
#14

## Any other comments?
Globally configured palm plugins are available outside of repos, this allows users to create their own 'setup' plugins as needed. It's worth noting that we probably want to implement some mechanism for global plugins to exclude themselves from the global scope, as those may depend on being in the context of a git project.

## Where has this been tested?

**Operating System:** MacOS

### CODE REVIEW

**Comment by jakeberesford-palmetto** [comment]
> * dn't exist and I would need to proceed manually. That was pretty confusing to me. But then it created a folder inside the folder with my new test project name and a bunch of things were generated there, so I guess it worked?

Thanks for testing!

I definitely need to iron out some bumps with the `new` command. TLDR is that I was trying to do things in palm that should happen within the cookie-cutter template (I learned this after I made that palmetto flavored dbt template) - I'll commit some fixes here this afternoon 🙂 

Overall, it sounds like the global palm works as intended, but the new command needs some love (and better documentation/help text)

**Comment by mariahjrogers** [comment]
This is looking a lot better. Still have some questionable results but it may be more to do with our cookiecutter template than this functionality.

I am still getting an error, though: 
```Initialized empty Git repository in /Users/mrogers-mac/dev/test_mariah/.git/
Name: palm-dbt
Version: 0.3.1
Summary: dbt extension for Palm CLI
Home-page: https://github.com/palmetto/palm-dbt
Author: Palmetto - Data & Analytics team
Author-email: data-analytics-team@palmetto.com
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: palm, pyyaml, sqlparse
Required-by: 
Traceback (most recent call last):
  File "/usr/local/bin/palm", line 5, in <module>
    from palm.cli import cli
  File "/usr/local/lib/python3.9/site-packages/palm/cli.py", line 17, in <module>
    palm_config = PalmConfig()
  File "/usr/local/lib/python3.9/site-packages/palm/palm_config.py", line 31, in __init__
    self._setup()
  File "/usr/local/lib/python3.9/site-packages/palm/palm_config.py", line 42, in _setup
    self.branch = self._get_current_branch()
  File "/usr/local/lib/python3.9/site-packages/palm/palm_config.py", line 67, in _get_current_branch
    return self.repo.head.shorthand
_pygit2.GitError: reference 'refs/heads/main' not found

Project initialized successfully!
```

**Comment by jakeberesford-palmetto** [comment]
> This is looking a lot better. Still have some questionable results but it may be more to do with our cookiecutter template than this functionality.
> 
> I am still getting an error, though:
> _pygit2.GitError: reference 'refs/heads/main' not found
> 
> Project initialized successfully!

This error occurs when a repo is found, but there are no commits yet. I'd like to get a fix in for that, even if just to raise a more useful error. I'll need to spend some time on it.

**Comment by mariahjrogers** [comment]
> This error occurs when a repo is found, but there are no commits yet.

Why would there be a repo found for a project that was just generated from nothing?

**Comment by jakeberesford-palmetto** [comment]
> Why would there be a repo found for a project that was just generated from nothing?

In the case of the dbt template I wrote, the repo isinitialized as part of the post_hooks: https://github.com/jakeberesford-palmetto/cookiecutter-dbt/blob/main/hooks/post_gen_project.py#L13

**Review by mariahjrogers — APPROVED** [review]
excellent!!

**Pull request merged**
